//例外を投げる関数

export const throwException = () => {
    //thwow文：意図的に例外（エラー）を発生させる
    throw new Error("エラー発生")
}